name: speedtest-cli
base: core18
summary: Command line interface for testing internet bandwidth using speedtest.net
description: |
  Command line interface for testing internet bandwidth using speedtest.net.
  
  https://github.com/sivel/speedtest-cli

  This is NOT an official distribution of speedtest-cli, refer the snap's own issue
  tracker for support:  
  https://github.com/Lin-Buo-Ren/speedtest-cli-snap/issue

grade: stable
confinement: strict
adopt-info: speedtest-cli

parts:
  speedtest-cli:
    after:
      - selective-checkout
    source: https://github.com/sivel/speedtest-cli.git
    source-depth: 100
    override-pull: |
      snapcraftctl pull

      "${SNAPCRAFT_STAGE}"/scriptlets/selective-checkout \
        --append-packaging-revision

    plugin: python
    prime:
      - -usr/share/man/
      - -usr/share/lintian/
      - -usr/share/pixmaps/

  launcher:
    source: launchers
    plugin: dump

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v2.0.2
    plugin: dump
    build-packages:
      # Scriptlet dependencies
      - curl
      - jq
      - sed

      # Uncomment the VCS your main part is using
      - git

    stage:
      - scriptlets/selective-checkout
    prime:
      - -*

apps:
  speedtest-cli:
    adapter: full
    command: bin/speedtest-cli
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command-chain:
      - speedtest-cli-launch

plugs:
  network:
