name: speedtest-cli
base: core18
summary: Command line interface for testing internet bandwidth using speedtest.net
description: |
  Command line interface for testing internet bandwidth using speedtest.net.
  
  https://github.com/sivel/speedtest-cli

  This is NOT an official distribution of speedtest-cli, refer the snap's own issue
  tracker for support:  
  https://github.com/Lin-Buo-Ren/speedtest-cli-snap/issue

grade: stable
confinement: strict
adopt-info: speedtest-cli

parts:
  speedtest-cli:
    after:
      - selective-checkout
    source: https://github.com/sivel/speedtest-cli.git
    source-depth: 100
    override-pull: |
      snapcraftctl pull

      "${SNAPCRAFT_STAGE}"/scriptlets/selective-checkout \
        --append-packaging-revision

    plugin: python
    prime:
      # whitelist matching, could minimize the snap size but requires
      # great understanding to what the application uses to work
      - bin/speedtest-cli
      - lib/python3.6/site-packages/pkg_resources/
      - lib/python3.6/site-packages/speedtest.py
      - lib/python3.6/site-packages/speedtest_cli-*.dist-info/
      - lib/*-linux-gnu/lib*.so*
      - usr/bin/python3*
      - usr/lib/python3.6/
      - usr/lib/*-linux-gnu/lib*.so*
      - usr/share/doc/*/copyright

      # blacklist matching, easier to trim out files that are trivially
      # unused, but will be unable to minimize the snap to the extreme
      # - -lib/python*/site-packages/pip*/
      # - -lib/python*/site-packages/setuptools*/
      # - -lib/python*/site-packages/wheel*/
      # - -usr/lib/python3.7/
      # - -usr/lib/python3.8/
      # - -usr/lib/valgrind/
      # - -usr/sbin/
      # - -usr/share/man/
      # - -usr/share/lintian/
      # - -usr/share/pixmaps/
      # - -usr/share/applications/
      # - -usr/share/bug/

  launchers:
    source: launchers
    plugin: dump
    organize:
      '*': bin/

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v2.0.2
    plugin: dump
    build-packages:
      # Scriptlet dependencies
      - curl
      - jq
      - sed

      # Uncomment the VCS your main part is using
      - git

    stage:
      - scriptlets/selective-checkout
    prime:
      - -*

apps:
  speedtest-cli:
    adapter: full
    command: bin/speedtest-cli
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command-chain:
      - bin/speedtest-cli-launch

plugs:
  network:
